import type { ScenarioDefinition } from "./types";

export const scenarios: ScenarioDefinition[] = [
  {
    id: "l3vpn-ce-to-ce",
    name: "L3VPN CE-to-CE",
    shortName: "L3VPN",
    description:
      "Customer traffic from CE3 traverses the aggregation and MPLS backbone to reach CE2. The full path CE → AGG → PE → P → P → PE → AGG → CE shows the two-label stack (VPN + transport) pushed at ingress PE, swapped at P routers, and popped (PHP) at egress PE.",
    category: "l3vpn",
    icon: "🏷️",
    color: "#3b82f6",
    concepts: [
      "MPLS label push/swap/pop",
      "VPN + Transport label stack",
      "Penultimate Hop Popping (PHP)",
      "VRF route lookup",
      "SR-MPLS forwarding",
    ],
    initialDscp: "ef",
    sourceDevice: "ce3",
    destDevice: "ce2",
    overlayType: "l3vpn",
  },
  {
    id: "l2vpn-pseudowire",
    name: "L2VPN Pseudowire (VPWS)",
    shortName: "L2VPN",
    description:
      "A point-to-point Ethernet pseudowire carries Layer 2 frames transparently between PE1 and PE2. The original Ethernet frame is encapsulated with a PW label (service demux) and a transport label (SR-MPLS forwarding). The control word ensures correct sequencing.",
    category: "l2vpn",
    icon: "🔗",
    color: "#14b8a6",
    concepts: [
      "Pseudowire encapsulation",
      "PW label + Transport label stack",
      "Control word",
      "Transparent L2 transport",
      "VPWS point-to-point service",
    ],
    sourceDevice: "ce1",
    destDevice: "ce4",
    overlayType: "l2vpn",
  },
  {
    id: "vxlan-ingress-replication",
    name: "VXLAN Ingress Replication",
    shortName: "VXLAN",
    description:
      "Layer 2 traffic between VXLAN VTEPs is encapsulated with a VXLAN header (VNI), UDP, and outer IP header. The original Ethernet frame rides inside the tunnel, enabling L2 extension across the IP fabric.",
    category: "vxlan",
    icon: "🔀",
    color: "#8b5cf6",
    concepts: [
      "VXLAN encapsulation/decapsulation",
      "VNI (Virtual Network Identifier)",
      "VTEP source/destination IPs",
      "Outer IP + UDP headers",
      "Ingress replication (BUM traffic)",
    ],
    sourceDevice: "pe1",
    destDevice: "pe2",
    overlayType: "vxlan",
  },
  {
    id: "sr-te-low-latency",
    name: "SR-TE Low-Latency Path",
    shortName: "SR-TE",
    description:
      "An SR-TE policy steers traffic along an explicit path using a segment list (stack of Node SIDs). Instead of following the IGP shortest path, the packet is guided hop-by-hop through the specified nodes.",
    category: "sr-te",
    icon: "🎯",
    color: "#ec4899",
    concepts: [
      "Segment Routing Traffic Engineering",
      "Explicit segment list",
      "Node SID resolution",
      "Binding SID",
      "IGP vs engineered path",
    ],
    sourceDevice: "pe1",
    destDevice: "pe2",
    explicitPath: ["pe1", "p1", "pe2"],
    overlayType: "l3vpn",
  },
  {
    id: "bgp-route-reflection",
    name: "BGP Route Reflection",
    shortName: "BGP RR",
    description:
      "An iBGP UPDATE message flows from PE1 to route reflector RR1, which reflects it to PE2. This solves the iBGP full-mesh scaling problem. Watch the BGP attributes (next-hop, AS-path, communities) as the UPDATE traverses the network.",
    category: "bgp",
    icon: "🔄",
    color: "#f59e0b",
    concepts: [
      "iBGP full mesh problem",
      "Route reflector client",
      "NEXT_HOP preservation",
      "Cluster ID loop prevention",
      "BGP UPDATE message flow",
    ],
    sourceDevice: "pe1",
    destDevice: "pe2",
    explicitPath: ["pe1", "rr1", "pe2"],
  },
  {
    id: "tilfa-failover",
    name: "TI-LFA Failover",
    shortName: "TI-LFA",
    description:
      "When the primary pe1→p1 link fails, TI-LFA provides sub-50ms protection by pre-computing a backup path. The packet is re-routed through an alternate path with a repair segment list, then converges to the new IGP shortest path.",
    category: "tilfa",
    icon: "🛡️",
    color: "#ef4444",
    concepts: [
      "Topology-Independent LFA",
      "Pre-computed backup path",
      "Repair segment (Node SID)",
      "Sub-50ms convergence",
      "Post-convergence path",
    ],
    sourceDevice: "pe1",
    destDevice: "pe2",
    overlayType: "l3vpn",
  },
  {
    id: "internet-transit",
    name: "Internet Transit via ASBR",
    shortName: "Internet",
    description:
      "Customer traffic destined for the internet exits the SP network via an ASBR peering with the upstream ISP. Watch the eBGP next-hop change at the AS boundary, and how the MPLS domain terminates at the ASBR.",
    category: "internet",
    icon: "🌐",
    color: "#06b6d4",
    concepts: [
      "eBGP peering at AS boundary",
      "AS-path prepending",
      "Next-hop change at ASBR",
      "MPLS domain boundary",
      "Transit routing",
    ],
    initialDscp: "be",
    sourceDevice: "ce2",
    destDevice: "isp-upstream",
    overlayType: "internet",
  },
];
